#!/usr/bin/env ruby

new_version = ARGV[0]
abort 'Please specify the new version as your first parameter' if new_version.nil? || new_version.strip == ''

version_file = 'lib/railsthemes/version.rb'
File.open(version_file, 'w') do |f|
  f.write <<-EOS
module Railsthemes
  unless defined?(Railsthemes::VERSION)
    VERSION = "#{new_version}"
  end
end
EOS
end

`git add #{version_file}`
`git commit -m "Bump version to #{new_version}"`
`git tag v#{new_version}`
`gem build railsthemes.gemspec`

puts <<-EOS
Now inspect the commits and
  git push
  git push --tags
  gem push railsthemes-#{new_version}.gem
EOS
